name: dp-transformers
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - ca-certificates=2023.7.22
  - cudatoolkit=11.6.0
  - intel-openmp=2022.1.0
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - mkl=2022.1.0
  - ncurses=6.4
  - openssl=3.0.10
  - pip=23.2.1
  - python=3.9.17
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - typing_extensions=4.7.1
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - adal==1.2.7
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - argcomplete==2.1.2
      - async-timeout==4.0.3
      - attrs==23.1.0
      - azure-common==1.1.28
      - azure-core==1.29.1
      - azure-graphrbac==0.61.1
      - azure-mgmt-authorization==3.0.0
      - azure-mgmt-containerregistry==10.1.0
      - azure-mgmt-core==1.4.0
      - azure-mgmt-keyvault==10.2.3
      - azure-mgmt-resource==22.0.0
      - azure-mgmt-storage==21.0.0
      - azureml-core==1.52.0
      - backports-tempfile==1.0
      - backports-weakref==1.0.post1
      - bcrypt==4.0.1
      - certifi==2023.7.22
      - cffi==1.15.1
      - charset-normalizer==3.2.0
      - contextlib2==21.6.0
      - cryptography==41.0.3
      - datasets==2.6.1
      - dill==0.3.5.1
      - docker==6.1.3
      - exceptiongroup==1.1.3
      - filelock==3.12.2
      - frozenlist==1.4.0
      - fsspec==2023.6.0
      - functorch==0.2.1
      - huggingface-hub==0.16.4
      - humanfriendly==10.0
      - idna==3.4
      - iniconfig==2.0.0
      - isodate==0.6.1
      - jeepney==0.8.0
      - jmespath==1.0.1
      - jsonpickle==3.0.2
      - knack==0.10.1
      - loralib==0.1.1
      - msal==1.23.0
      - msal-extensions==1.0.0
      - msrest==0.7.1
      - msrestazure==0.6.4
      - multidict==6.0.4
      - multiprocess==0.70.13
      - ndg-httpsclient==0.5.1
      - numpy==1.25.2
      - oauthlib==3.2.2
      - opacus==1.2.0
      - opt-einsum==3.3.0
      - packaging==23.0
      - pandas==2.0.3
      - paramiko==3.3.1
      - pathspec==0.11.2
      - pkginfo==1.9.6
      - pluggy==1.2.0
      - portalocker==2.7.0
      - prv-accountant==0.1.1.post1
      - pyarrow==12.0.1
      - pyasn1==0.5.0
      - pycparser==2.21
      - pygments==2.16.1
      - pyjwt==2.8.0
      - pynacl==1.5.0
      - pyopenssl==23.2.0
      - pysocks==1.7.1
      - pytest==7.4.0
      - python-dateutil==2.8.2
      - pytz==2023.3
      - pyyaml==6.0.1
      - regex==2023.8.8
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - responses==0.18.0
      - scipy==1.11.1
      - secretstorage==3.3.3
      - six==1.16.0
      - tabulate==0.9.0
      - tokenizers==0.13.3
      - tomli==2.0.1
      - tqdm==4.66.1
      - transformers==4.28.1
      - tzdata==2023.3
      - urllib3==1.26.16
      - websocket-client==1.6.1
      - xxhash==3.3.0
      - yarl==1.9.2
