name: dp-transformers-examples-nlg-reddit
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2021.7.5
  - cudatoolkit=10.2.89
  - ffmpeg=4.3
  - freetype=2.10.4
  - gmp=6.2.1
  - gnutls=3.6.15
  - intel-openmp=2021.3.0
  - jpeg=9b
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.2
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - ncurses=6.2
  - nettle=3.7.3
  - ninja=1.10.2
  - numpy-base=1.20.3
  - olefile=0.46
  - openh264=2.1.0
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - pillow=8.3.1
  - pip=21.0.1
  - python=3.8.11
  - pytorch=3.9.1
  - readline=8.1
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.10
  - torchaudio=0.9.1
  - torchvision=0.10.1
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - aiohttp==3.7.4.post0
    - artifacts-keyring==0.3.1
    - async-timeout==3.0.1
    - attrs==21.2.0
    - cffi==1.14.6
    - chardet==4.0.0
    - charset-normalizer==2.0.6
    - click==8.0.1
    - cryptography==35.0
    - datasets==2.0.0
    - dill==0.3.4
    - filelock==3.1.0
    - fsspec==2021.9.0
    - huggingface-hub==0.10.1
    - idna==3.2
    - importlib-metadata==4.8.1
    - jeepney==0.7.1
    - joblib==1.0.1
    - keyring==23.2.1
    - multidict==5.1.0
    - multiprocess==0.70.12.2
    - numpy==1.21.2
    - opacus==0.15.0
    - pandas==1.3.3
    - pyarrow==5.0.0
    - pycparser==2.20
    - python-dateutil==2.8.2
    - pytz==2021.1
    - pyyaml==5.4.1
    - regex==2021.9.24
    - requests==2.26.0
    - sacremoses==0.0.46
    - scipy==1.7.1
    - secretstorage==3.3.1
    - tokenizers==0.11.1
    - tqdm==4.62.3
    - transformers==4.20.1
    - typing_extensions==4.0.1
    - urllib3==1.26.7
    - xxhash==2.0.2
    - yarl==1.6.3
    - zipp==3.5.0
