name: Test examples environment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example: [
          "examples/nlg-reddit/sample-level-dp",
          "examples/nlg-reddit/author-level-dp"
        ]
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: conda-incubator/setup-miniconda@8ee1f361103df19b6f8c8655fd3967a8ecb162d5 # v4.0.1
      with:
        activate-environment: env
        environment-file: ${{ matrix.example }}/environment.yml
        auto-activate-base: false
    - name: Install package
      run: |
        /usr/share/miniconda/envs/env/bin/pip install -e .
