name: Test examples

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install azure-cli
        az extension add -n ml
        az login --service-prinicipal -u ${{ secrets.AZ_CLIENT_ID }} -p ${{ secrets.AZ_CLIENT_PASSWORD }} --tenant ${{ secrets.AZ_TENANT_ID }}
        az account --set ${{ secrets.AZ_SUBSCRIPTION_ID }}
        az configure --defaults group=${{ secrets.AZ_RESOURCE_GROUP }} workspace=${{ secrets.AZ_WORKSPACE_NAME }}
        python -m pip install pytest pytest-xdist azureml-core
    - name: Run examples with pytest
      run: |
        pytest -n 16 examples -v --junitxml=junit/test-results.xml
