name: Test examples environment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example: [
          "examples/nlg-reddit/sample-level-dp",
          "examples/nlg-reddit/author-level-dp"
        ]
    steps:
    - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
    - uses: conda-incubator/setup-miniconda@9f54435e0e72c53962ee863144e47a4b094bfd35 # v2.3.0
      with:
        activate-environment: env
        environment-file: ${{ matrix.example }}/environment.yml
        auto-activate-base: false
    - name: Install package
      run: |
        /usr/share/miniconda/envs/env/bin/pip install -e .
