name: Test examples

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example: [
          "examples/nlg-reddit/sample-level-dp",
          "examples/nlg-reddit/author-level-dp"
        ]
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: env
        environment-file: ${{ matrix.example }}/environment.yml
        auto-activate-base: false
    - name: Check conda environments
      run: |
        conda env list
    - name: Check packages
      run: |
        conda activate env && which pip
        conda activate env && pip freeze 
    - name: Install package
      run: |
        conda activate env && pip install -e .
    - name: Check environment
      run: |
        conda activate env && python -c "import torch"
        conda activate env && python -c "import dp-transformers"
